<a href="https://colab.research.google.com/github/harshsinghdev-11/machine_learning/blob/main/tensorFlowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [3]:
scaler = tf.constant(5)
print(tf.rank(scaler))

tf.Tensor(0, shape=(), dtype=int32)


In [4]:
vector = tf.constant([1,23,3,4])
print(tf.rank(vector))

tf.Tensor(1, shape=(), dtype=int32)


In [5]:
matrix = tf.constant([[1,23],[23,432]])
print(tf.rank(matrix))

tf.Tensor(2, shape=(), dtype=int32)


In [8]:
tensor_3d = tf.constant([[[12,2],[213,32]],[[23,45],[43,43]]])
print(tf.rank(tensor_3d))

tf.Tensor(3, shape=(), dtype=int32)


In [12]:
A = tf.constant([1,2,3,4,5])
B=tf.constant([3,4,56,6,343])

In [13]:
sum_result = tf.add(A,B)
print(sum_result)

tf.Tensor([  4   6  59  10 348], shape=(5,), dtype=int32)


In [14]:
sub_result = tf.subtract(A,B)
print(sub_result)

tf.Tensor([  -2   -2  -53   -2 -338], shape=(5,), dtype=int32)


In [15]:
elem_mul = tf.multiply(A,B)
print(elem_mul)

tf.Tensor([   3    8  168   24 1715], shape=(5,), dtype=int32)


In [17]:
A_reshaped = tf.reshape(A,(1,-1))
B_reshaped = tf.reshape(B,(-1,1))

In [18]:
mat_mul = tf.matmul(A_reshaped,B_reshaped)
print(mat_mul)

tf.Tensor([[1918]], shape=(1, 1), dtype=int32)
